module.exports = {
  projects: [
    '<rootDir>/apps/kroton',
    '<rootDir>/libs/web-shell-feature',
    '<rootDir>/libs/web-shell-ui-layout',
    '<rootDir>/libs/web-shell-ui-unauthorized-layout',
    '<rootDir>/libs/web/shell/ui/top-bar',
    '<rootDir>/libs/web/shell/ui/unauthorized-top-bar',
    '<rootDir>/libs/web/shell/ui/unauthorized-main-view',
    '<rootDir>/libs/web/shared/ui/button',
    '<rootDir>/libs/web/unauthorized-home/feature',
    '<rootDir>/libs/web/shell/ui/footbar',
    '<rootDir>/libs/web/sign-in/feature',
    '<rootDir>/libs/web/sign-up/feature',
    '<rootDir>/libs/web/shell/ui/main-view',
    '<rootDir>/libs//web/shared/data-access/store',
    '<rootDir>/libs/web/shell/utils/guards/unauthorized-guard',
    '<rootDir>/libs//web/shell/ui/module-menu',
  ],
};
